#!/data/data/hilled.pwnterm/files/usr/bin/bash

# cd into lemon and install deps
cd /data/data/hilled.pwnterm/files/usr/opt/l3mon

echo "Postinstall for l3mon..."
sleep 5
npm install pm2 -g
sleep 1
npm install

echo "###"
echo "# README - L3MON"
echo "# USER: admin"
echo "# PASW: toor"
echo "# WEB: 127.0.0.1:22533"
echo "###"
sleep 5

echo "Done..."
